### PR TITLE
Add Guaraní sign for PYG

### PR DESCRIPTION
**Pull request by hisapy**
Hi @liuggio 

Can you please accept this PR so we can use your lib in Paraguay ?
😃

### CODE REVIEW

**Comment by Nitrino** [comment]
@hisapy Thanks! 👍

**Comment by hisapy** [comment]
Hey devs @Nitrino and @liuggio, can you please release this to Hex? or can I somehow help you to release it?

**Comment by Nitrino** [comment]
Hi @hisapy, sorry for the delay. 
I published v1.3.2 https://hex.pm/packages/money/1.3.2

**Comment by hisapy** [comment]
Thanks a lot @Nitrino ... this pretty little lib is being useful in 2 projects in Paraguay now :)

**Pull request merged**
