### PR TITLE
Fixing Mexican and Colombian pesos names

### PR DESCRIPTION
**Pull request by jordi-adame**

### CODE REVIEW

**Comment by Nitrino** [comment]
Cool, thanks for the correction!

**Comment by danschultzer** [comment]
@jordi-adame why did you change the exponent for all the updated currencies? Only CLF has 10000 subunits per unit.

**Comment by Nitrino** [comment]
Oh, I also did not notice. Fixed in #64.
@jordi-adame Have a look, please. 
I was guided by this standard https://www.currency-iso.org/en/home/tables/table-a1.html

**Comment by jordi-adame** [comment]
@danschultzer @Nitrino you're right. In Mexico we have to use 4 for money conversions and tax collecting activities but it's not a general requirement

**Pull request merged**
