### PR TITLE
Add support currency exponents

### PR DESCRIPTION
**Pull request by Nitrino**
This PR added support currency exponents according to [IOS 4217](https://www.currency-iso.org/en/home/tables/table-a1.html)

### CODE REVIEW

**Comment by Nitrino** [comment]
Hi. This library is alive? 
We use it for their own projects and I would like to help the development of

**Comment by liuggio** [comment]
@andrewtimberlake WDYT about this?

**Comment by liuggio** [comment]
thanks @Nitrino sorry about this....

**Comment by Nitrino** [comment]
@liuggio Thanks for the answer.
Now I am a lot of working with money in elixir. So I would be happy to your reviews and to add new features(e.g. currency exchange, currency codes) to the library, instead of the wrappers in my project

**Comment by Nitrino** [comment]
@liuggio @andrewtimberlake what about PR? 
Maybe I can help maintain that library?

**Comment by Nitrino** [comment]
Is there any progress on a review that PR?

**Comment by jordi-adame** [comment]
@Nitrino i don't think this is maintained anymore, we are also dealing with the same issue

**Comment by Nitrino** [comment]
@jordi-adame Yep, this library is not supported.
I decided to [fork](https://github.com/Nitrino/elixir_money) the library and continue to develop. In the next few days I will finish refactoring and several improvements and release on hex.pm

**Comment by liuggio** [comment]
@jordi-adame would you like to be a core dev of this lib?

**Comment by Nitrino** [comment]
@liuggio maybe I can be useful in core team?

**Comment by liuggio** [comment]
@Nitrino would be awesome!

**Comment by Nitrino** [comment]
@liuggio cool, thanks!

**Comment by jordi-adame** [comment]
@liuggio yes! we'd love to do that

**Pull request merged**
